### ISSUE TITLE
Enable pylint in CI

### ISSUE THREAD

**Issue by nedrebo** [zivid/python-samples#8]
requirements.txt was left out of date, but CI did not detect it.

Hopefully pylint would have detected that, and anyway it would be nice to have pylint enabled in this repository.

**Comment by nedrebo** [comment]
FYI: @trym-b

**Comment by trym-b** [comment]
It is easy to add, but I don't want to make the CI here so complicated that the regular users of this repo does not understand what is going on.

**Comment by SatjaSivcev** [comment]
Maybe we can try and see how it goes?

**Comment by nedrebo** [comment]
> It is easy to add, but I don't want to make the CI here so complicated that the regular users of this repo does not understand what is going on.

Then they need to learn. Better that than broken repository for end users. #6 breaks master, and master in cpp-extra-samples is already broken (https://github.com/zivid/cpp-extra-samples/issues/1#issuecomment-511924511). Better that we struggle with getting code merged than that customers struggle using our code. We aim for high quality and simplicity, CI is the simplest way I know of to achieve that.

**Comment by trym-b** [comment]
This issue has been fixed
